### ISSUE TITLE
NullReferenceException on HangingWiresMod.Event_ChunksLoaded

### ISSUE THREAD

**Issue by Craluminum2413** [VonZeeple/Signals#2]
From `server-main.txt`
```
13.7.2022 02:07:24 [Fatal] System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.API.Util.ArrayExtensions.Contains[T](T[] array, T value)
   at signals.src.hangingwires.HangingWiresMod.Event_ChunksLoaded(Vec2i chunkCoord, IWorldChunk[] chunks)
   at Vintagestory.API.Common.ChunkColumnLoadedDelegate.Invoke(Vec2i chunkCoord, IWorldChunk[] chunks)
   at Vintagestory.Server.ServerSystemSupplyChunks.<>c__DisplayClass15_0.<loadOrGenerateChunkColumn>b__0()
   at Vintagestory.Server.ServerMain.ProcessMainThreadTasks()
   at Vintagestory.Server.ServerMain.ProcessMain()
   at Vintagestory.Server.ServerMain.Process()
```

**Comment by VonZeeple** [comment]
Can you provide some context please?

**Comment by Craluminum2413** [comment]
I get this on loading any world

**Comment by Craluminum2413** [comment]
You need this have enabled I think
![image](https://user-images.githubusercontent.com/69315569/178819763-2cd6d235-dc66-4e97-9432-38db971007ff.png)

**Comment by Craluminum2413** [comment]
It happens every time I load new chunks with mod enabled
